feat: add invoice service
kayobruno/minha-quadra pull request #43
Opened 2024-07-15 23:54 UTC by WebertySilveira

2024-07-17 00:51 UTC, kayobruno requested changes

2024-07-17 00:51 UTC, kayobruno commented on app/Services/InvoiceService.php
Please, add unit tests for this class.
No test, no beer! 🍺

2024-07-17 00:51 UTC, kayobruno commented on app/Services/InvoiceService.php
> +use phpDocumentor\Reflection\Types\Collection;
Are you sure if the import of this class is correct?

2024-07-17 00:51 UTC, kayobruno commented on app/Services/InvoiceService.php
> +    public function findById(string $id): Model
You can use the `Invoice` like return type.

2024-07-17 00:51 UTC, kayobruno commented on app/Services/InvoiceService.php
> +    public function save(DataParam $dataParam): Model
same as above

2024-07-17 00:51 UTC, kayobruno commented on app/Services/InvoiceService.php
> +    public function update(string $id, DataParam $dataParam): Model
same as above

2024-07-17 00:51 UTC, kayobruno commented on app/Services/InvoiceService.php
> +    public function update(string $id, DataParam $dataParam): Model
You can use the `InvoiceData` like param type.

2024-07-17 00:51 UTC, kayobruno commented on app/Services/InvoiceService.php
> +    public function save(DataParam $dataParam): Model
You can use the `InvoiceData` like param type.

2024-07-21 16:03 UTC, closed without merging

2024-07-21 16:04 UTC, WebertySilveira commented
It was necessary to combine service and repository as they depend on each other